Import and Data Creation

Setup : Import and Data Creation

In [3]:
import numpy as np
import pandas as pd

# Days and Products
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
products = ['Bread', 'Cakes', 'Cookies', 'Muffins', 'Pies']

# Sales data (rows=days, columns=products)
sales_data = np.array([
    [20, 15, 50, 10, 5],
    [25, 18, 55, 12, 6],
    [22, 16, 52, 11, 7],
    [30, 20, 60, 15, 10],
    [35, 25, 65, 20, 15],
    [40, 30, 70, 25, 18]
])

# Convert to DataFrame for a clean table
sales_df = pd.DataFrame(sales_data, index=days, columns=products)

# Cost and Selling Prices
cost_prices = np.array([10, 50, 5, 12, 20])
selling_prices = np.array([15, 70, 8, 18, 30])

print(sales_df)



           Bread  Cakes  Cookies  Muffins  Pies
Monday        20     15       50       10     5
Tuesday       25     18       55       12     6
Wednesday     22     16       52       11     7
Thursday      30     20       60       15    10
Friday        35     25       65       20    15
Saturday      40     30       70       25    18


1. Total items sold for each product

In [4]:
total_items = np.sum(sales_data,axis=0)
print("Total items sold:",dict(zip(products,total_items)))

Total items sold: {'Bread': 172, 'Cakes': 124, 'Cookies': 352, 'Muffins': 93, 'Pies': 61}


2. Average items sold per product

In [5]:
average_items = np.mean(sales_data,axis=0)
print("Average items sold:",dict(zip(products,average_items)))

Average items sold: {'Bread': 28.666666666666668, 'Cakes': 20.666666666666668, 'Cookies': 58.666666666666664, 'Muffins': 15.5, 'Pies': 10.166666666666666}


3. Total Revenue

In [6]:
total_revenue = np.sum(total_items*selling_prices)
print("Total Revenue of the week : $",total_revenue)

Total Revenue of the week : $ 17580


4. Profit of each product

In [7]:
profit_per_item = selling_prices - cost_prices
total_profit = np.sum(total_items*profit_per_item)

print("Total profit of the week: $",total_profit)

Total profit of the week: $ 5564


5. Maximum number of items sold for any product

In [8]:
max_sold = np.max(sales_data)
print("Maximum items sold in a day for any product:",max_sold)

Maximum items sold in a day for any product: 70


6. Add Leftover Inventory Dataset

In [10]:
leftover_inventory = np.array([5,2,10,3,1])

total_inventory_used = total_items = np.sum(sales_data,axis=0) + leftover_inventory

print("Leftover Invemtory at end of the week:")
print(dict(zip(products,leftover_inventory)))

print("\n Total Inventory used (Sales + Leftovers):")
print(dict(zip(products,total_inventory_used)))
print("\n")


Leftover Invemtory at end of the week:
{'Bread': 5, 'Cakes': 2, 'Cookies': 10, 'Muffins': 3, 'Pies': 1}

 Total Inventory used (Sales + Leftovers):
{'Bread': 177, 'Cakes': 126, 'Cookies': 362, 'Muffins': 96, 'Pies': 62}




7. Create Sales Data for 2 weeks

In [12]:
sales_data_week2 = sales_data.copy()

combined_sales_data = np.vstack((sales_data,sales_data_week2))

day_weeks = ['Monday_2', 'Tuesday_2', 'Wednesday_2', 'Thursday_2', 'Friday_2', 'Saturday_2']

all_days = days + day_weeks

combined_sales_df = pd.DataFrame(combined_sales_data, index=all_days, columns=products)

print("Combinde Sales Data for Two weeks:")
print(combined_sales_df)


Combinde Sales Data for Two weeks:
             Bread  Cakes  Cookies  Muffins  Pies
Monday          20     15       50       10     5
Tuesday         25     18       55       12     6
Wednesday       22     16       52       11     7
Thursday        30     20       60       15    10
Friday          35     25       65       20    15
Saturday        40     30       70       25    18
Monday_2        20     15       50       10     5
Tuesday_2       25     18       55       12     6
Wednesday_2     22     16       52       11     7
Thursday_2      30     20       60       15    10
Friday_2        35     25       65       20    15
Saturday_2      40     30       70       25    18


8. Weekday vs Weekend Sales

In [13]:
weekday_sales = sales_data[:5]
weekend_sales = sales_data[5:]

weekday_total = np.sum(weekday_sales)
weekend_total = np.sum(weekend_sales)

print("Total weekday sales:", weekday_total)
print("Total weekend sales:", weekend_total)


Total weekday sales: 619
Total weekend sales: 183


In [ ]:
9. Separate product cost prices

In [14]:

high_value_products = ['Cakes', 'Pies']
high_value_indices = [products.index(p) for p in high_value_products]
high_value_cost_prices = cost_prices[high_value_indices]


low_value_products = ['Bread', 'Cookies', 'Muffins']
low_value_indices = [products.index(p) for p in low_value_products]
low_value_cost_prices = cost_prices[low_value_indices]


print("High-Value Product Cost Prices:")
print(dict(zip(high_value_products, high_value_cost_prices)))

print("\nLow-Value Product Cost Prices:")
print(dict(zip(low_value_products, low_value_cost_prices)))
print("\n")

High-Value Product Cost Prices:
{'Cakes': 50, 'Pies': 20}

Low-Value Product Cost Prices:
{'Bread': 10, 'Cookies': 5, 'Muffins': 12}




10. Day with highest pies sold

In [16]:
pie_sales = sales_data[:, 4]
max_pies_day = days[np.argmax(pie_sales)]
print("Day with highest pies sold:",max_pies_day)

Day with highest pies sold: Saturday


 11. Days where more than 60 cookies were sold


In [17]:
cookie_sales = sales_data[:, 2]
days_more_than_60_cookies = [days[i] for i in range(len(days)) if cookie_sales[i] > 60]
print("Days with more than 60 cookies sold:", days_more_than_60_cookies)

Days with more than 60 cookies sold: ['Friday', 'Saturday']


12. Muffins least to most sold

In [18]:
muffin_sales = sales_data[:, 3]
sorted_muffins = sorted(zip(muffin_sales, days))
print("Muffins sales sorted:", sorted_muffins)

Muffins sales sorted: [(10, 'Monday'), (11, 'Wednesday'), (12, 'Tuesday'), (15, 'Thursday'), (20, 'Friday'), (25, 'Saturday')]


13. Bread sales best to worst

In [19]:
bread_sales = sales_data[:, 0]
sorted_bread = sorted(zip(bread_sales, days), reverse=True)
print("Bread sales sorted best to worst:", sorted_bread)

Bread sales sorted best to worst: [(40, 'Saturday'), (35, 'Friday'), (30, 'Thursday'), (25, 'Tuesday'), (22, 'Wednesday'), (20, 'Monday')]


14. Wednesday sales

In [20]:
wednesday_sales = sales_data[2]
print("Wednesday sales:", dict(zip(products, wednesday_sales)))

Wednesday sales: {'Bread': 22, 'Cakes': 16, 'Cookies': 52, 'Muffins': 11, 'Pies': 7}


In [ ]:
15. Weekend Muffins sales (Saturday only)

In [21]:
weekend_muffins = sales_data[5, 3]
print("Muffin sales on Saturday:", weekend_muffins)

Muffin sales on Saturday: 25


16. Reorder the daily sales data based on bread sales, showing the best-performing days first.

In [32]:
bread_sales = sales_data[:, 0]  
sorted_indices = np.argsort(bread_sales)[::-1]  
reordered_sales_data = sales_data[sorted_indices]
reordered_days = np.array(days)[sorted_indices]

print("Reordered sales data based on bread sales:")
for i in range(len(reordered_days)):
    print(f"{reordered_days[i]}: {reordered_sales_data[i]}")

print("\n")

Reordered sales data based on bread sales:
Saturday: [40 30 70 25 18]
Friday: [35 25 65 20 15]
Thursday: [30 20 60 15 10]
Tuesday: [25 18 55 12  6]
Wednesday: [22 16 52 11  7]
Monday: [20 15 50 10  5]




17. Extract the sales data for Wednesday to analyze the mid-week performance.


In [33]:
wednesday_sales = sales_data[2]  
print("Wednesday's sales data:", wednesday_sales)
print("\n")

Wednesday's sales data: [22 16 52 11  7]




18. Duplicate and simulate 10% demand increase

In [22]:
sales_data_copy = sales_data.copy()
increased_sales_data = (sales_data_copy * 1.1).astype(int)
print("Increased Sales Data:\n", increased_sales_data)

Increased Sales Data:
 [[22 16 55 11  5]
 [27 19 60 13  6]
 [24 17 57 12  7]
 [33 22 66 16 11]
 [38 27 71 22 16]
 [44 33 77 27 19]]


 19. Confirm original unchanged

In [23]:
print("Original Sales Data:\n", sales_data)

Original Sales Data:
 [[20 15 50 10  5]
 [25 18 55 12  6]
 [22 16 52 11  7]
 [30 20 60 15 10]
 [35 25 65 20 15]
 [40 30 70 25 18]]


 20. Flatten into single row

In [24]:
flattened_sales = sales_data.flatten()
print("Flattened sales:", flattened_sales)

Flattened sales: [20 15 50 10  5 25 18 55 12  6 22 16 52 11  7 30 20 60 15 10 35 25 65 20
 15 40 30 70 25 18]


21. Change structure: (6 days × 5 products) → (5 rows × 6 columns)

In [25]:
reshaped_sales = sales_data.reshape(5,6)
print("Reshaped Sales Data (5x6):\n", reshaped_sales)

Reshaped Sales Data (5x6):
 [[20 15 50 10  5 25]
 [18 55 12  6 22 16]
 [52 11  7 30 20 60]
 [15 10 35 25 65 20]
 [15 40 30 70 25 18]]


22. Identity matrix (promotional discount example)

In [26]:
identity_matrix = np.identity(5)
adjusted_cost = cost_prices * identity_matrix
print("Adjusted Cost Prices Matrix:\n", adjusted_cost)

Adjusted Cost Prices Matrix:
 [[10.  0.  0.  0.  0.]
 [ 0. 50.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.]
 [ 0.  0.  0. 12.  0.]
 [ 0.  0.  0.  0. 20.]]


23. Diagonal matrix for revenu

In [27]:
revenue_diag = np.diag(total_items * selling_prices)
print("Revenue Diagonal Matrix:\n", revenue_diag)

Revenue Diagonal Matrix:
 [[2655    0    0    0    0]
 [   0 8820    0    0    0]
 [   0    0 2896    0    0]
 [   0    0    0 1728    0]
 [   0    0    0    0 1860]]


24. Change the structure of the sales data to have 5 rows and 7 columns instead of 7 rows and 5 columns, ensuring the data integrity is maintained.


In [34]:
sales_data_with_sunday = np.vstack([sales_data, np.zeros(5)])
reshaped_sales_data = sales_data_with_sunday.T
new_days = days + ["Sunday"]
combined_data = np.vstack((reshaped_sales_data, new_days))

print("Reshaped sales data (5 rows x 7 columns):")
print(combined_data)
print("\n")

Reshaped sales data (5 rows x 7 columns):
[['20.0' '25.0' '22.0' '30.0' '35.0' '40.0' '0.0']
 ['15.0' '18.0' '16.0' '20.0' '25.0' '30.0' '0.0']
 ['50.0' '55.0' '52.0' '60.0' '65.0' '70.0' '0.0']
 ['10.0' '12.0' '11.0' '15.0' '20.0' '25.0' '0.0']
 ['5.0' '6.0' '7.0' '10.0' '15.0' '18.0' '0.0']
 ['Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday']]




25. Apply a 5x5 matrix where the diagonal values represent a specific product’s promotional discount (use identity values). Calculate the adjusted cost prices.

In [35]:
discount_matrix = np.identity(5) * 0.9  # 10% discount for all products
adjusted_cost_prices = cost_prices * np.diag(discount_matrix)

print("Adjusted cost prices after discount:", adjusted_cost_prices)
print("\n")



Adjusted cost prices after discount: [ 9.  45.   4.5 10.8 18. ]




26. Use a diagonal matrix to highlight the importance of individual products based on their contribution to revenue.

In [36]:
weekly_revenue = np.sum(sales_data * selling_prices, axis=0)
total_revenue = np.sum(weekly_revenue)
importance_weights = weekly_revenue / total_revenue
importance_matrix = np.diag(importance_weights)

print("Importance matrix based on revenue contribution:")
print(importance_matrix)
print("\n")

Importance matrix based on revenue contribution:
[[0.14675768 0.         0.         0.         0.        ]
 [0.         0.49374289 0.         0.         0.        ]
 [0.         0.         0.16018203 0.         0.        ]
 [0.         0.         0.         0.09522184 0.        ]
 [0.         0.         0.         0.         0.10409556]]




27. Create a diagonal structure representing the selling prices of the products and use it to calculate the revenue in a new way.

In [37]:
selling_price_matrix = np.diag(selling_prices)
daily_revenue_matrix = sales_data @ selling_price_matrix
weekly_revenue_alt = np.sum(daily_revenue_matrix, axis=0)

print("Weekly revenue calculated using selling price matrix:", weekly_revenue_alt)
print("\n")


Weekly revenue calculated using selling price matrix: [2580 8680 2816 1674 1830]




28. Replace Friday's sales with avg of Mon-Thu

In [28]:
average_mon_thu = np.mean(sales_data[0:4], axis=0)
sales_data_modified = sales_data.copy()
sales_data_modified[4] = average_mon_thu.astype(int)
print("Sales data after replacing Friday:\n", sales_data_modified)

Sales data after replacing Friday:
 [[20 15 50 10  5]
 [25 18 55 12  6]
 [22 16 52 11  7]
 [30 20 60 15 10]
 [24 17 54 12  7]
 [40 30 70 25 18]]


29. Compare total weekday sales to total weekend sales for all products.

In [38]:
weekday_sales = np.sum(sales_data[:5], axis=0)  # Monday to Friday
weekend_sales = np.sum(sales_data[5:], axis=0)  # Saturday

print("Weekday vs. Weekend Sales (Total):")
for i in range(len(products)):
    print(f"{products[i]}: Weekday = {weekday_sales[i]}, Weekend = {weekend_sales[i]}")
print("\n")

Weekday vs. Weekend Sales (Total):
Bread: Weekday = 132, Weekend = 40
Cakes: Weekday = 94, Weekend = 30
Cookies: Weekday = 282, Weekend = 70
Muffins: Weekday = 68, Weekend = 25
Pies: Weekday = 43, Weekend = 18




30. Identify which product sells the most during the weekend compared to weekdays.

In [39]:
weekend_vs_weekday_diff = weekend_sales - weekday_sales
most_sold_product_index = np.argmax(weekend_vs_weekday_diff)
most_sold_product = products[most_sold_product_index]

print("Product with the highest sales difference (weekend vs. weekday):", most_sold_product)

Product with the highest sales difference (weekend vs. weekday): Pies
